name: Labseq-Exercise
services: 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    working_dir: /code
    entrypoint: [ "mvn", "clean", "quarkus:dev" ]
    restart: always 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: always
